# Generated by Django 5.0.2 on 2024-02-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='  _price',
            new_name='price',
        ),
    ]
